### ISSUE TITLE
Create a css framework

### ISSUE THREAD

**Issue by Olivia-Chiong** [100Automations/Website#111]
### Overview
Create a css framework so developers can refer to it and build consistently beautiful websites.

### Action Items
- [ ] Create a framework using Material Design
- [ ] Review with the team

**Comment by Olivia-Chiong** [comment]
@ExperimentsInHonesty will connect @mdothman with Josh Bubar and David Rubenstein for some css help.

**Comment by NivenPrasad** [comment]
@mdothman, @CamilaArias and @Olivia-Chiong meeting on 1/14 to discuss.

**Comment by mdothman** [comment]
@mdothman is meeting with Josh Bubar on 1/14 for style guidance.

**Comment by mdothman** [comment]
# 100 Automations CSS Framework

## Overview

The purpose of this report is to provide the reader with a design system and style guide the project. We will not be using a css framework, instead we will be designing our own framework using SASS.

## Class Names

Class names will be semantic and descriptive.

| Class | Description |
| ----- | ----------- |
|  |
## Folder System

Since Jekyll is compatible with SASS, we will be creating two files to maintain our styles.
> _sass
> assets/css

The >_sass is responsible for our imports and css variables, and our css file will be used for our >_site output.

### Still in progress  . . .

**Comment by mdothman** [comment]
@CamilaArias and @mdothman will be meeting to discuss class names and folder structure on 1/17

**Comment by NivenPrasad** [comment]
@mdothman and @CamilaArias aiming for classes and design system to be set up by Saturday 1/23.

**Comment by mdothman** [comment]
# Class Naming System

## Overview

This is a report for establishing the fundamental naming system of 100 Automations. 100 Automations will have a component based naming system for the purpose of future modification.

### Class names

```html
<div class="title className variable" ></div>
```

- Class names will be composed of three components:
  - A title displaying site purpose
  - A class name describing component
  - A variable describing styling

## 100 Automations Class Names

The purpose of this table is to describe relevant styles used to implement Material Design Lite components.

| Label | Title  | Class Name | Variable | Folder |
|-------|--------|------------|----------|--------|
| Header Container | | mdl-layout | | includes/header.scss |
| Header | oaw_header | mdl-layout__header | mdl-layout__header--transparent | includes/header.scss |
| Footer | oaw_footer| mdl-mini-footer | | includes/footer.scss |
| Action Card| action | mdl-card | | includes/actionCard.scss |
| Border Card| border | mdl-card | | includes/border.scss |
| Automation Card| atoCard | mdl-card | | includes/atoCard.scss |
| Guide Card | guideCard | mdl-card | | includes/guideCard.scss|

### Customized components

These are the required components that must be styled.

```css
 <style>
 /* Header Container */
.mdl-layout {
 color: white;
 };

 /* Website Header */
 .oaw_header .mdl-layout__header {
 position: absolute;
 color: 87% black;
 };
 
 /* Website footer */
 .oaw_footer .mdl-mini-footer {
 position: absolute;
 color:
 };
 
 /* Action Card */
 .action .mdl-card {
 
 /* Card background */
 position: absolute;
 };
 
 /* Border Card */
 .border .mdl-card {};
 
 /* Automation Card */
 .atoCard .mdl-card {};
 
 /* Guide Card */
 .guideCard .mdl-card {};
 </style>
```

### Still in progress . . .
