### ISSUE TITLE
A proposal for streamlining the process of adding a new guide page OR project page/card.

### ISSUE THREAD

**Issue by akibrhast** [100Automations/Website#189]
### Dependency
- Post MVP

> _While the below proposal is going to be discussed in terms of the particularity of the guide pages. It can also be applied easily to new project cards that needs creation._

## Tentative Steps

1. Create an endpoint with a form, and https://quilljs.com/
2. In the form make these fields required. [title,description,status,display] and also ask for their github username
3. Let them write out their article/guide page in the quiljs section.(we could also do a template renderer here)
4. On submit ensure that the github username supplied in the form exists in the github username section of the onboarding spread sheet.
5. If it exists create a new issue on GitHub using the data from the form with label 'newguidepage' . For example.
<details>
<summary>Example New Issue That will be created</summary>

```yaml
---
title: Writing an Article for Your Automation
description: If you want to write an article about your automation, consider these tips.
status: in progress
display: true
---
CONTENT GOES HERE THAT WAS WRITTEN IN QUILLJS THIS SHOULD ALREADY BE IN HTML FORMAT (WHICH THE GITHUB ISSUE RENDERS PERFECTLY)
```
</details>

6. Discussion/Edits between folks on the content of the article. No styling discussions needed cause that has been standardized.
7. Discussion Ends and Finalized. a 'finalized' label is added to the issue
8. A github action checks for issues labeled 'newguidepage' + 'finalized' that has been labeled finalized for over an hour+ , extracts the markdown from the issue. And creates a new pull request by creating a markdown file with the name specified in the title in the respected folder. The pull request should of course link to the issue.
9. Another github action get notified of this pull request and runs an action that merges the new guide pages into master from within the context of the action. Takes screen shots of what the new guide page woud look like on the live site in chrome, edge, firefox, mobile, desktop, tablet. and adds the images as a comment to the pull request.
10. A developer riding the subway looks at the pull request from his cell while enjoying a delicious cup of coffee in the cold winter morning and.
11. MERGE.

## What that boils down to.
1. Someone writes and article
2. It goes through revision
3. Its merged

> **Anyone can get started on writing an article without worrying about understand or needing to learn markdown and formatting and this and that(and by anyone I mean anyone in the team -- pms,ux,ui,content,dev,research,etc....)**

_p.s. I already have a script that does yaml validation, we can use on either project cards or guide page front matter_
